server:
  port: 8086

spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yml

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false

  datasource-shard1:
      url: jdbc:postgresql://localhost:5432/transactionshard1
      username: postgres
      password: 4

  datasource-shard2:
    url: jdbc:postgresql://localhost:5432/transactionshard2
    username: postgres
    password: 4
