Server:
  port: 8086

spring:
  datasource:
    shard1:
      url: jdbc:postgresql://localhost:5432/transactionshard1
      username: postgres
      password: 4
    shard2:
      url: jdbc:postgresql://localhost:5432/transactionshard2
      username: postgres
      password:  4
  flyway:
    enabled: false

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
